# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: 'src/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'src/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --filter TestCategory!=Integration'

- task: CmdLine@2
  displayName: Push
  inputs:
    script: |
      dotnet nuget push -s https://api.nuget.org/v3/index.json -k $(NuGetApiKey) src/**/*.nupkg